blueprint:
  name: DEVICE - AutoOFF.
  description: Apaga un dispositivo después de un tiempo de espera.
  domain: automation
  input:
    target_device:
      name: Target
      description: Dispostivo a controlar.
      selector:
        entity:
          domain: 
            - switch
            - light
    delay_time:
      name: Tiempo de espera
      description: Tiempo transcurrido antes de apagar el dispositivo.
      default: 1
      selector:
        select:
          options:
            - label: 1 minuto
              value: "1"
            - label: 5 minutos
              value: "5"
            - label: 10 minutos
              value: "10"
            - label: 15 minutos
              value: "15"
            - label: 30 minutos
              value: "30"
            - label: 1 hora
              value: "60"
    operation_mode:
      name: Modo de operación
      description: Cuándo se ejecuta la automatización.
      default: daytime
      selector:
        select:
          options:
            - label: Solo durante el día (Default)
              value: "daytime"
            - label: Todo el tiempo
              value: "all_day"

variables:
  operation_mode: !input operation_mode

trigger:
  - platform: state
    entity_id: !input target_device
    to: 'on'
 
condition:
  condition: and  # 'twilight' condition: dusk and dawn, in typical locations
  conditions:
    - "{{ (operation_mode == 'daytime') }}"
    #- condition: template
    #  value_template: "{{ state_attr('sun.sun', 'elevation') < 0 }}"
    #- condition: template
    #  value_template: "{{ state_attr('sun.sun', 'elevation') > -6 }}"
    - condition: sun
      after: sunrise
      after_offset: "01:00:00"
    - condition: sun
      before: sunset
      before_offset: "-01:00:00"

action:
  - delay: 
      minutes: !input delay_time
  - service: homeassistant.turn_off
    target:
      entity_id: !input target_device

mode: restart
max_exceeded: silent