blueprint:
  name: LIGHTS - Ramdom
  description: "Enciende y apaga una luz de forma aleatoria durante la noche para simular que hay alguien en casa."
  domain: automation
  input:
    target_light:
      name: Dispositivo
      description: "Luz que se encenderá y apagará aleatoriamente."
      selector:
        entity:
          domain: 
            - light
            - switch
    start_time:
      name: Hora de inicio
      description: "Hora a la que comenzará la simulación."
      default: "22:00:00"
      selector:
        time: {}
    end_time:
      name: Hora de fin
      description: "Hora a la que terminará la simulación."
      default: "06:00:00"
      selector:
        time: {}
    min_duration:
      name: Tiempo mínimo
      description: "Duración mínima que la luz permanecerá encendida."
      default: 15
      selector:
        number:
          min: 10
          max: 30
          step: 5
          unit_of_measurement: minutes
    max_duration:
      name: Tiempo máximo
      description: "Duración máxima que la luz permanecerá encendida."
      default: 45
      selector:
        number:
          min: 30
          max: 60
          step: 5
          unit_of_measurement: minutes

mode: restart

variables:
  min_duration: !input min_duration
  max_duration: !input max_duration

trigger:
  - platform: time
    at: !input start_time

condition: []

action:
  - repeat:
      while:
        - condition: time
          after: !input start_time
          before: !input end_time
      sequence:
        - service: homeassistant.turn_on
          target:
            entity_id: !input target_light
        - delay:
            minutes: "{{ range(min_duration, max_duration) | random }}"
        - service: homeassistant.turn_off
          target:
            entity_id: !input target_light
        - delay:
            minutes: "{{ range(min_duration, max_duration) | random }}"
  - condition: time
    after: !input end_time

