blueprint:
  name: LIGHT - Randomised Light at Night
  description: Randomly toggles a light at night within set parameters
  domain: automation
  input:
    target_light:
      name: Target Light
      description: Luz a controlar
      selector:
        entity:
          domain:
            - light
            - switch
    night_sensor:
      name: Night binary sensor
      description: sensor binario de noche 
      selector:
        entity:
          domain:
            - binary_sensor
    
    start:
      name: Start Time
      description: Hora de inicio
      selector:
        time:

    end:
      name: End Time 
      description: Hora de finalización
      selector:
        time:

    min_time:
      name: Min Time ON / OFF
      description: Tiempo minimo de encendio o apagado
      default: 15
      selector:
        number:
          min: 10
          max: 30
          step: 5
          unit_of_measurement: minutes

    max_time:
      name: Max Time ON / OFF
      description: Tiempo máximo de endendido o apagado
      default: 30
      selector:
        number:
          min: 10
          max: 30
          step: 5
          unit_of_measurement: minutes

    away_lighting_switch_entity:
      name: Away Lighting Switch
      description: Switch de ausencia. 
      selector:
        entity:
          domain:
            - input_boolean
            - switch
    trigger_minutes:
      name: Trigger Minutes
      description: How often should this automation run?
      default: 30
      selector:
        number:
          step: 5
          min: 30
          max: 60
          unit_of_measurement: minutes
    random_delay_max_minutes:
      name: Random Delay Maximum Minutes
      description: What is the maximum time limit for the random delay?
      default: 30
      selector:
        number:
          step: 5
          min: 10
          max: 30
          unit_of_measurement: minutes
    lights_out_time:
      name: Lights Out Time
      description: What time does this automation stop running? Must be before midnight 23:59:59.
      selector:
        time:

mode: single
max_exceeded: silent

variables:
  trigger_minutes: !input trigger_minutes
  random_delay_max_minutes: !input random_delay_max_minutes

  start: !input start_time
  end: !input end_time

  min_time: !input min_time
  max_time: !input max_time
  night_sensor: !input night_sensor


  
trigger:
  - platform: time_pattern
    minutes: /1

condition:
  - condition: template
    value_template: '{{ now().minute % trigger_minutes == 0 }}'
  - condition: state
    entity_id: !input override_switch_entity
    state: 'off'
  - condition: state
    entity_id: night_sensor
    state: 'on'
  - condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '-2.0'
    
action:
  - choose:
      - conditions:
          - condition: time
            before: end
          - condition: time
            after: start
        sequence:
          - delay:
              minutes: "{{ range(min_time,max_time) | random }}"
          - choose:
              - conditions:
                  - condition: state
                    entity_id: night_sensor
                    state: 'on'
                sequence:
                  - service: homeassistant.toggle
                    target:
                      entity_id: !input target_light
            default: []
    default:
      - condition: state
        entity_id: !input target_light
        state: 'on'
      - delay:
          minutes: "{{ range(min_time,max_time) | random }}"
      - choose:
          - conditions:
              - condition: state
                entity_id: night_sensor
                state: 'on'
            sequence:
              - service: homeassistant.turn_off
                target:
                  entity_id: !input target_light
        default: []